package com.tech.hospitality.domain;

// Generated 9 Jun, 2016 10:48:52 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

/**
 * Billingdetails generated by hbm2java
 */
@Entity
@Table(name = "billingdetails", catalog = "healthcare")
public class Billingdetails implements java.io.Serializable {

	private Integer id;
	private Userbilling userbilling;
	private String type;
	private String name;
	private String amount;

	public Billingdetails() {
	}

	public Billingdetails(Userbilling userbilling, String type, String name,
			String amount) {
		this.userbilling = userbilling;
		this.type = type;
		this.name = name;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billing_id", nullable = false)
	@Cascade(value=org.hibernate.annotations.CascadeType.ALL)
	public Userbilling getUserbilling() {
		return this.userbilling;
	}

	public void setUserbilling(Userbilling userbilling) {
		this.userbilling = userbilling;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "amount", length = 45)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

}
