package com.tech.hospitality.domain;

// Generated 9 Jun, 2016 10:48:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;

/**
 * Userbilling generated by hbm2java
 */
@Entity
@Table(name = "userbilling", catalog = "healthcare")
public class Userbilling implements java.io.Serializable {

	private Integer id;
	private User user;
	private String amount;
	private Date date;
	private Set<Billingdetails> billingdetailses = new HashSet<Billingdetails>(
			0);

	public Userbilling() {
	}

	public Userbilling(User user, String amount, Date date,
			Set<Billingdetails> billingdetailses) {
		this.user = user;
		this.amount = amount;
		this.date = date;
		this.billingdetailses = billingdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	@Cascade(value=org.hibernate.annotations.CascadeType.ALL)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "amount", length = 45)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userbilling", cascade= CascadeType.ALL)
	public Set<Billingdetails> getBillingdetailses() {
		return this.billingdetailses;
	}

	public void setBillingdetailses(Set<Billingdetails> billingdetailses) {
		this.billingdetailses = billingdetailses;
	}

}
